GET  http://localhost:3000/suggestion/

###

GET  http://localhost:3000/suggestion?username=geraldo

###

GET  http://localhost:3000/suggestion/2

###

POST  http://localhost:3000/suggestion
content-type: application/json

{
    "text": "estuda edição de videos"
}
###

PUT  http://localhost:3000/suggestion/2
###

DELETE  http://localhost:3000/suggestion/3